export const genres = {
  movie: [
    { id: 1, name: "Em Alta", nameWithoutAccents: "em-alta" },
    { id: 28, name: "Ação", nameWithoutAccents: "acao" },
    { id: 12, name: "Aventura", nameWithoutAccents: "aventura" },
    { id: 16, name: "Animação", nameWithoutAccents: "animacao" },
    { id: 35, name: "Comédia", nameWithoutAccents: "comedia" },
    { id: 80, name: "Crime", nameWithoutAccents: "crime" },
    { id: 99, name: "Documentário", nameWithoutAccents: "documentario" },
    { id: 18, name: "Drama", nameWithoutAccents: "drama" },
    { id: 10751, name: "Família", nameWithoutAccents: "familia" },
    { id: 14, name: "Fantasia", nameWithoutAccents: "fantasia" },
    { id: 36, name: "História", nameWithoutAccents: "historia" },
    { id: 27, name: "Terror", nameWithoutAccents: "terror" },
    { id: 10402, name: "Musical", nameWithoutAccents: "musical" },
    { id: 9648, name: "Mistério", nameWithoutAccents: "misterio" },
    { id: 10749, name: "Romance", nameWithoutAccents: "romance" },
    { id: 878, name: "Ficção científica", nameWithoutAccents: "ficcao-cientifica" },
    { id: 10770, name: "Telefilme", nameWithoutAccents: "telefilme" },
    { id: 53, name: "Suspense", nameWithoutAccents: "suspense" },
    { id: 10752, name: "Guerra", nameWithoutAccents: "guerra" },
    { id: 37, name: "Faroeste", nameWithoutAccents: "faroeste" },
  ],
  tv: [
    { id: 1, name: "Em Alta", nameWithoutAccents: "em-alta" },
    { id: 10759, name: "Ação e Aventura", nameWithoutAccents: "acao-aventura" },
    { id: 16, name: "Animação", nameWithoutAccents: "animacao" },
    { id: 35, name: "Comédia", nameWithoutAccents: "comedia" },
    { id: 80, name: "Crime", nameWithoutAccents: "crime" },
    { id: 99, name: "Documentário", nameWithoutAccents: "documentario" },
    { id: 18, name: "Drama", nameWithoutAccents: "drama" },
    { id: 10751, name: "Família", nameWithoutAccents: "familia" },
    { id: 10762, name: "Infantil", nameWithoutAccents: "infantil" },
    { id: 9648, name: "Mistério", nameWithoutAccents: "misterio" },
    { id: 10763, name: "Notícias", nameWithoutAccents: "noticias" },
    { id: 10764, name: "Reality Show", nameWithoutAccents: "reality-show" },
    { id: 10765, name: "Ficção Científica e Fantasia", nameWithoutAccents: "ficcao-cientifica-fantasia" },
    { id: 10766, name: "Novela", nameWithoutAccents: "novela" },
    { id: 10767, name: "Talk Show", nameWithoutAccents: "talk-show" },
    { id: 10768, name: "Guerra e Política", nameWithoutAccents: "guerra-politica" },
    { id: 37, name: "Faroeste", nameWithoutAccents: "faroeste" },
  ],
};

